### ISSUE TITLE
StaticmanLab and custom domain

### ISSUE THREAD

**Issue by radekkozak** [VincentTam/TestStaticmanLab#12]
Hi, is there any chance to got this working with custom domain ? 

Right now i got it working in my test repo https://radekkozak.github.io/staticman/

But the moment i use identical setup but with github pages that has custom domain -> it breaks and i get Internal Server Error 500 in the browser

Thanks

**Comment by radekkozak** [comment]
Sniffing around i managed to find more exact error i get with such setup (the minute i switch back to using github.io domain it works again)

{"success":false,"rawError":{"_smErrorCode":"ERROR_PROCESSING_ENTRY"},"errorCode":"ERROR_PROCESSING_ENTRY"}

**Comment by VincentTam** [comment]
@radekkozak Thank you for your interest in my API instance, which runs on a free Heroku dyno.

My answer won't be too technical since IT isn't my field.  I'm sorry I don't really know the source of error now.  I'll look into the log later.

From my limited knowledge about Staticman v3, using custom web site domain and custom GitHub/GitLab domain, say the official Popcorn demo.

**Comment by radekkozak** [comment]
Hi, thanks for letting me know. Yes, i looked at all the examples but v2 is no-go unfortunatelly because it is impossible to get the green light from collaboration bot - problem that seems to be BIG for everyone these days. @staticmanlab goes through but then again - the above mentioned. 

Anywho, thanks again, and i'll be grateful for any kind of info from logs that might shed some light on the problem

**Comment by VincentTam** [comment]
@radekkozak Here's the entries related to your GitHub repos in log file for yesterday, which you've asked for.  (I've stripped off sensitive info.)  Hope this helps.

Regarding the `ERROR_PROCESSING_ENTRY`, since this repo is simply a demo to showcase the functionalities of Staticman v3 (development version), it's better to raise this issue in either the original Staticman project (if you think that's the problem of the stable/development version) or my fork (if you think that's specific to my own API instance).  Since I've kept [my changes minimal](https://github.com/eduardoboucas/staticman/compare/dev...VincentTam:deploy), I think the former is a better choice.

My comments:

1. Migration to GitLab is a way to circumvent @staticmanapp's problem (detailed in eduardoboucas/Staticman#222) since GitLab does not have collaborator invites.  In fact, support for GitLab has become the _most_ wanted feature.  (c.f. eduardoboucas/Staticman#22)
2. Please take a look at the endpoint schemes in eduardoboucas/Staticman#219 to avoid 404 errors.
  - `GET /v3/connect/github/user/repo`
  - `POST /v3/connect/gitlab/user/repo/branch/property` (using `GET` will give you a 404 error)
  - Although adding parameters in URL for a POST request to the `/entry` endpoint works, it's better to avoid this.
  - I've tried RESTClient, but it *doesn't* work.  You may try other clients like Postman, but I *won't* be able to respond to any problems arised in the testing.

Attachment:
[gh-log.txt](https://github.com/VincentTam/TestStaticmanLab/files/2449622/gh-log.txt)

**Comment by samarulmeu** [comment]
@radekkozak Can you please check that you don't have `notifications` enabled in `staticman.yml`?
I got the same error, but on a subdomain on GitLab so no custom domain. I disabled notifications and everything is working.
