### ISSUE TITLE
Error while trying to submit comment.

### ISSUE THREAD

**Issue by sachin10101998** [VincentTam/TestStaticmanLab#28]
{"success":false,"rawError":{"_smErrorCode":"GITHUB_CREATING_PR"},"errorCode":"GITHUB_CREATING_PR"}
The above error shows up when I try to submit a comment.
Any fixes?

**Comment by VincentTam** [comment]
@sachin10101998 Thanks for your attention.  I'm sorry for such errors.  I didn't notice that since I was testing on GitLab & Framagit.  I had been testing merging recent changes on Staticman repo between PR 219 and before issue 243.  Something inside caused error.  Need further investigation.  Now I've rolled back my instance to the version in December to resume service ASAP.  Closing due to recently created comment #29.

In the future, I'll do my testing on my Framagit first.
